### ISSUE TITLE
Multiple HSA IDs for one row in get_nodes() when original type is a gene

### ISSUE THREAD

**Issue by ethanmclark1** [noriakis/pykegg#1]
Hello, 

I am relatively new to the field of bioinformatics and biology as a whole so this may be a dumb question but I'm trying to build a GNN model using this repo. When I retrieve a pathway and then get nodes from that pathway, there are some rows in the nodes data frame that have multiple graphic names as well as multiple HSA tags associated with it. My intuition on the multiple graphics names is that there are different naming conventions but when it comes to HSA tags, I assumed that would have to be unique?

![Screenshot 2024-04-11 103351](https://github.com/noriakis/pykegg/assets/50840394/cc449162-9a0e-4ec7-a2b7-0339843700ab)

In this image, the original type of the node is a gene yet there are still multiple HSA tags to go with it, so I think I am missing something but I'm not sure.

**Comment by noriakis** [comment]
Hello,

Thanks for using the library. For details, please refer to the [KEGG PATHWAY database description](https://www.genome.jp/kegg/pathway.html), which states that organism-specific pathways like HSA are generated by converting KEGG ORTHOLOGYs to gene identifiers. Thus, as you stated, one node in the KEGG PATHWAY can have multiple identifiers (name or graphics name). The `pykegg` fetches KEGG PATHWAY information using [`biopython`](https://biopython.org/docs/1.75/api/Bio.KEGG.KGML.KGML_parser.html) library, and `biopython` also has multiple identifiers in one node. 

I hope this helps.
